/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupsIndexRouteImport } from './routes/startups.index'
import { Route as StartupsIdRouteImport } from './routes/startups.$id'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsIndexRoute = StartupsIndexRouteImport.update({
  id: '/startups/',
  path: '/startups/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsIdRoute = StartupsIdRouteImport.update({
  id: '/startups/$id',
  path: '/startups/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/insights': typeof InsightsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workflow': typeof WorkflowRoute
  '/startups/$id': typeof StartupsIdRoute
  '/startups/': typeof StartupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/insights': typeof InsightsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workflow': typeof WorkflowRoute
  '/startups/$id': typeof StartupsIdRoute
  '/startups': typeof StartupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/insights': typeof InsightsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workflow': typeof WorkflowRoute
  '/startups/$id': typeof StartupsIdRoute
  '/startups/': typeof StartupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assignments'
    | '/insights'
    | '/saved'
    | '/settings'
    | '/sources'
    | '/workflow'
    | '/startups/$id'
    | '/startups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assignments'
    | '/insights'
    | '/saved'
    | '/settings'
    | '/sources'
    | '/workflow'
    | '/startups/$id'
    | '/startups'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assignments'
    | '/insights'
    | '/saved'
    | '/settings'
    | '/sources'
    | '/workflow'
    | '/startups/$id'
    | '/startups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  InsightsRoute: typeof InsightsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  WorkflowRoute: typeof WorkflowRoute
  StartupsIdRoute: typeof StartupsIdRoute
  StartupsIndexRoute: typeof StartupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/': {
      id: '/startups/'
      path: '/startups'
      fullPath: '/startups/'
      preLoaderRoute: typeof StartupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/$id': {
      id: '/startups/$id'
      path: '/startups/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof StartupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssignmentsRoute: AssignmentsRoute,
  InsightsRoute: InsightsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  WorkflowRoute: WorkflowRoute,
  StartupsIdRoute: StartupsIdRoute,
  StartupsIndexRoute: StartupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
